from flask import Flask, request, jsonify, render_template
import cv2
import numpy as np
import tempfile
import os

from mindar import Detector, Matcher
from mindar.types import DetectorConfig, MatcherConfig


app = Flask(__name__, static_folder=".", static_url_path="", template_folder=".")

MODEL_PATH = "assets/targets.mind"


# ============================================================
# MINDAR CONFIGURATION
# ============================================================

detector_config = DetectorConfig(
    method="super_hybrid",
    max_features=1000,
    debug_mode=False
)

matcher_config = MatcherConfig(
    ratio_threshold=0.75,
    min_matches=8,
    debug_mode=False
)


detector = Detector(detector_config)
matcher = Matcher(matcher_config)


# ============================================================
# LOAD MIND FILE
# ============================================================

if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError(
        f"Missing {MODEL_PATH}"
    )


# ============================================================
# LOAD TARGET DATA
# ============================================================

# The package documents loading a compiled .mind file
# through MindARCompiler.
from mindar.compiler import MindARCompiler

compiler = MindARCompiler(
    debug_mode=False
)

mind_data = compiler.load_mind_file(
    MODEL_PATH
)

targets = mind_data["dataList"]

print(
    f"Loaded {len(targets)} target(s) from {MODEL_PATH}"
)


# ============================================================
# HOME
# ============================================================

@app.route("/")
def home():
    return render_template("index.html")


# ============================================================
# IMAGE CHECK
# ============================================================

@app.route("/check", methods=["POST"])
def check_image():

    if "image" not in request.files:
        return jsonify({
            "success": False,
            "error": "No image uploaded."
        }), 400


    uploaded_file = request.files["image"]


    if uploaded_file.filename == "":
        return jsonify({
            "success": False,
            "error": "No image selected."
        }), 400


    # --------------------------------------------------------
    # Read uploaded image
    # --------------------------------------------------------

    image_bytes = uploaded_file.read()

    image_array = np.frombuffer(
        image_bytes,
        dtype=np.uint8
    )

    image = cv2.imdecode(
        image_array,
        cv2.IMREAD_GRAYSCALE
    )


    if image is None:
        return jsonify({
            "success": False,
            "error": "The uploaded file is not a valid image."
        }), 400


    # --------------------------------------------------------
    # Detect features
    # --------------------------------------------------------

    try:

        detection = detector.detect(image)

    except Exception as error:

        return jsonify({
            "success": False,
            "error": f"Detection error: {error}"
        }), 500


    feature_points = detection.get(
        "feature_points",
        []
    )


    # --------------------------------------------------------
    # No features
    # --------------------------------------------------------

    if len(feature_points) == 0:

        return jsonify({
            "success": True,
            "matched": False,
            "status": "FAIL",
            "message": "No recognizable image features found.",
            "features": 0
        })


    # --------------------------------------------------------
    # Match against targets
    # --------------------------------------------------------

    best_match = None


    for target_index, target in enumerate(targets):

        try:

            # The exact target structure is determined by the
            # .mind file generated by MindAR.

            match_result = matcher.match(
                detection,
                target
            )


            if not match_result:
                continue


            # Try to obtain match count from the result.

            match_count = 0

            if isinstance(match_result, dict):

                match_count = (
                    match_result.get("match_count")
                    or match_result.get("matches")
                    or match_result.get("num_matches")
                    or 0
                )

                if isinstance(match_count, list):
                    match_count = len(match_count)


            else:

                try:
                    match_count = len(match_result)
                except Exception:
                    match_count = 0


            if (
                best_match is None
                or match_count > best_match["matches"]
            ):

                best_match = {
                    "target": target_index,
                    "matches": int(match_count)
                }


        except Exception as error:

            print(
                f"Target {target_index} matching error:",
                error
            )


    # ========================================================
    # RESULT
    # ========================================================

    if best_match is not None:

        # Minimum threshold.
        # You can increase this if you want stricter matching.

        MIN_MATCHES = 8


        if best_match["matches"] >= MIN_MATCHES:

            return jsonify({

                "success": True,

                "matched": True,

                "status": "PASS",

                "message": "Target matched successfully.",

                "targetIndex":
                    best_match["target"],

                "matches":
                    best_match["matches"],

                "features":
                    len(feature_points)

            })


    # --------------------------------------------------------
    # FAIL
    # --------------------------------------------------------

    return jsonify({

        "success": True,

        "matched": False,

        "status": "FAIL",

        "message": "Image does not match any target.",

        "features":
            len(feature_points)

    })


# ============================================================
# START
# ============================================================

if __name__ == "__main__":

    print("")
    print("========================================")
    print("       MINDAR IMAGE CHECKER")
    print("========================================")
    print("")
    print(f"Target file: {MODEL_PATH}")
    print(f"Targets loaded: {len(targets)}")
    print("")
    print("Open:")
    print("http://127.0.0.1:5000")
    print("")

    app.run(
        host="127.0.0.1",
        port=5000,
        debug=True
    )